---
slug: tfm_doc
filename: tfm_doc
title: Despliegue de una aplicación Ruby on Rails utilizando las tecnologías de virtualización Docker y CoreOS en la nube pública de Amazon Web Services
subtitle: Change me
description: Change me.
author: 
copyright: 2016
uuid: e1512a64-aa58-4996-a9da-5209e8ba7c13
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
